/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutRegisterImport } from './routes/_layout/register'
import { Route as LayoutKycImport } from './routes/_layout/kyc'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRegisterRoute = LayoutRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutKycRoute = LayoutKycImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/kyc': {
      id: '/_layout/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof LayoutKycImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/register': {
      id: '/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoutRegisterImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutKycRoute: typeof LayoutKycRoute
  LayoutRegisterRoute: typeof LayoutRegisterRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutKycRoute: LayoutKycRoute,
  LayoutRegisterRoute: LayoutRegisterRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/kyc': typeof LayoutKycRoute
  '/register': typeof LayoutRegisterRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesByTo {
  '/kyc': typeof LayoutKycRoute
  '/register': typeof LayoutRegisterRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/kyc': typeof LayoutKycRoute
  '/_layout/register': typeof LayoutRegisterRoute
  '/_layout/': typeof LayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/kyc' | '/register' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/kyc' | '/register' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/kyc'
    | '/_layout/register'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/kyc",
        "/_layout/register",
        "/_layout/"
      ]
    },
    "/_layout/kyc": {
      "filePath": "_layout/kyc.tsx",
      "parent": "/_layout"
    },
    "/_layout/register": {
      "filePath": "_layout/register.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
